### ISSUE TITLE
Missing tornado dep

### ISSUE THREAD

**Issue by naufraghi** [bdarnell/plop#22]
Just after install the viewer gives this error:
```
(py-env)[naufraghi@odello src]$ python -m plop.viewer --datadir=demo/profiles
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/naufraghi/.virtualenvs/py-env/lib/python2.7/site-packages/plop/viewer.py", line 7, in <module>
    from tornado.ioloop import IOLoop
ImportError: No module named tornado.ioloop
```
After `pip install tornado` it goes on as expected.

**Comment by bdarnell** [comment]
This is documented in the readme. I didn't want to make the whole package depend on tornado because the collector and viewer are often run separately, and I don't want the collector to have any extra requirements.

**Comment by naufraghi** [comment]
Ok, sorry, skipped the row.

Indeed perhaps a managed error message can offer a better user experience.
