### ISSUE TITLE
What about IO and threads?

### ISSUE THREAD

**Issue by szuliq** [bdarnell/plop#30]
The docs say (https://docs.python.org/2/library/signal.html) that it won't cover running threads nor blocking operations.

Do you plan on covering those in some way?

**Comment by bdarnell** [comment]
The signal callback is on the main thread, but plop collects data from all threads when the signal fires. If the main thread does a lot of uninterruptible I/O (there's an important distinction between "blocking" and "uninterruptible" I/O) then that will interfere with data collection, but it mostly works.

**Comment by szuliq** [comment]
Thanks for the answer and clearing this up for me!
